# Generated by Django 5.1.1 on 2024-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
