# Generated by Django 5.1.1 on 2024-09-07 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "blood_bank_app",
            "0002_alter_appuser_email_alter_appuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_superadmin",
        ),
    ]
