# Generated by Django 5.1.1 on 2024-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blood_bank_app",
            "0003_remove_appuser_is_active_remove_appuser_is_admin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
