# Generated by Django 5.1.1 on 2024-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_bank_app", "0005_donationcenter_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("days_remaining", models.IntegerField()),
            ],
        ),
    ]
