# Generated by Django 5.1.1 on 2024-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_bank_app", "0006_bloodinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcenter",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donationcenter",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
