# Generated by Django 5.1.1 on 2024-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_bank_app", "0007_donationcenter_latitude_donationcenter_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationcenter",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="donationcenter",
            name="longitude",
        ),
        migrations.AddField(
            model_name="donationcenter",
            name="map_image",
            field=models.ImageField(blank=True, null=True, upload_to="map_images/"),
        ),
    ]
